services:
  planner:
    container_name: trufi-planner
    build:
      context: ..
      dockerfile: trufi-server-planner/Dockerfile
    volumes:
      - ./web:/app/web
    restart: unless-stopped
    mem_limit: 2g
    # ports:
    #   - 8080:8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  default:
    name: trufi-server
